;--
; Supervisorctl configuration for starting 'scheduler' process.
;   - runs the '/jper/scheduler.py' file
;--

[program:scheduler]
command=/usr/local/PubRouter/app/bin/python -m router.jper.scheduler
user=jenkins
directory=/usr/local/PubRouter/deployment
stdout_logfile=/var/log/pubrouter/supervisor-%(program_name)s-access.log
; stderr_logfile=/var/log/pubrouter/supervisor-%(program_name)s-error.log
stderr_logfile=NONE
autostart=true
autorestart=true
stopasgroup=true
logfile_backups=5
logfile_maxbytes=10000000