;--
; Supervisorctl configuration for starting 'sword2' (SWORD-IN) - note this runs it using the gunicorn web-server.
;--

[program:sword-in]
command=/usr/local/PubRouter/app/bin/gunicorn -c /usr/local/PubRouter/deployment/sword-in_gconf.py "router.jper_sword_in.main:make_app()" --preload
user=jenkins
directory=/usr/local/PubRouter/deployment
stdout_logfile=/var/log/pubrouter/supervisor-%(program_name)s-access.log
stderr_logfile=/var/log/pubrouter/supervisor-%(program_name)s-error.log
; stderr_logfile=NONE
autostart=true
autorestart=true
stopasgroup=true
logfile_backups=5
logfile_maxbytes=10000000
