;--
; Supervisorctl configuration for starting 'sword-out'.
;--

[program:sword-out]
command=/usr/local/PubRouter/app/bin/python -m router.jper_sword_out.main
directory=/usr/local/PubRouter/deployment
user=jenkins
stdout_logfile=/var/log/pubrouter/supervisor-%(program_name)s-access.log
;stderr_logfile=/var/log/pubrouter/supervisor-%(program_name)s-error.log
stderr_logfile=NONE
autostart=true
autorestart=true
stopasgroup=true
logfile_backups=5
logfile_maxbytes=10000000