;--
; Supervisorctl configuration for starting 'harvester' process, which runs on a schedule.
;   - runs the '/jper/harvester/scheduler.py' file passing params that define the hour, minute it is to run:
;       - Hour
;       - Minutes
;--

[program:harvester]
command=/usr/local/PubRouter/app/bin/python -m router.harvester.harvester_main
user=jenkins
directory=/usr/local/PubRouter/deployment
stdout_logfile=/var/log/pubrouter/supervisor-%(program_name)s-access.log
stderr_logfile=/var/log/pubrouter/supervisor-%(program_name)s-error.log
autostart=true
autorestart=true
stopasgroup=true
logfile_backups=5
logfile_maxbytes=10000000