;--
; Supervisorctl configuration for starting 'xweb' - note this runs it using the gunicorn web-server.
;--

[program:xweb]
command=/usr/local/PubRouter/app/bin/gunicorn -c /usr/local/PubRouter/deployment/gconf.py "router.jper.web_main:make_app()" --preload
user=jenkins
directory=/usr/local/PubRouter/deployment
stdout_logfile=/var/log/pubrouter/supervisor-%(program_name)s-access.log
stderr_logfile=/var/log/pubrouter/supervisor-%(program_name)s-error.log
autostart=true
autorestart=true
stopasgroup=true
logfile_backups=5
logfile_maxbytes=10000000