;--
; Supervisorctl configuration for starting 'store' - note this runs it using the gunicorn web-server.
;--

[program:store]
command=/usr/local/PubRouter/app/bin/gunicorn -c /usr/local/PubRouter/deployment/store_gconf.py router.store.app:app
directory=/usr/local/PubRouter/deployment
user=jenkins
stdout_logfile=/var/log/pubrouter/supervisor-%(program_name)s-access.log
stderr_logfile=/var/log/pubrouter/supervisor-%(program_name)s-error.log
autostart=true
autorestart=true
stopasgroup=true
logfile_backups=5
logfile_maxbytes=10000000